const express = require("express");
const controller = require("../controllers/brand.controller");
const { requireAuth } = require("../middleware/authMiddleware");
const { requireRole, ROLES } = require("../middleware/roleMiddleware");
const router = express.Router();
router.get("/", controller.getAllBrands);
router.get("/:id", requireAuth, controller.getBrandById);
router.post("/", controller.createBrand);
router.put("/:id", controller.updateBrand);
router.delete("/:id", controller.deleteBrand);
module.exports = router;
